# Generated by Django 4.2.5 on 2024-08-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='poster')),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('actors', models.CharField(max_length=300, unique=True)),
                ('trailer_link', models.URLField(max_length=250, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaapp.category')),
            ],
        ),
    ]
