# Generated by Django 4.2.5 on 2024-08-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0005_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='pic',
        ),
    ]
