# Generated by Django 4.2.5 on 2024-08-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0006_rename_image_review_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='pic',
            new_name='photo',
        ),
    ]
